sudo: false
os:
 - linux
# Temporarily disable osx builds in Travis CI because of very long wait times
# - osx
language: d
d:
 - ldc
 - dmd
 - ldc-beta
 - dmd-nightly
 - dmd-beta
env:
 - ARCH="x86_64"
matrix:
  include:
    - {os: linux, d: ldc, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
    - {os: linux, d: dmd, env: ARCH="x86", addons: {apt: {packages: [[gcc-multilib]]}}}
  allow_failures:
    - {d: dmd, env: ARCH="x86"}
branches:
  only:
    - master
script:
 - dub test --arch "$ARCH"
 - dub build --root=examples/flex_plot
 # - dub build --root=examples/flex_plot/flex_common_pack

build_script:
 - echo dummy build script - dont remove me
 #- sed 's/"to_be_filled"/"Flex_logging", "Flex_logging_hex"/' -i dub.json
 # For now only python 3.4 is supported with pyd
 - sed 's/python35/python34/' -i examples/flex_plot.d
 # - sed 's/python35/python34/' -i examples/flex_plot/flex_common_pack/dub.json
